### ISSUE TITLE
Am I doing, it wrong?

### ISSUE THREAD

**Issue by pranavbhuv** [thebigsmileXD/MapAPI#13]
Step 1: Download plugin.
Step 2: Upload Plugin to Server.
Step 3. Start server.
Step 4. Check Files, and see new folder *maps*
Step 5. Insert PNG (images.png) file in folder next too idcounts.json
Step 6. Restart Server.
Step 7. Do /map create images.png
Step 8. Shows error about some route 

Anything I'm doing wrong?

**Comment by inxomnyaa** [comment]
Closing as invalid.
>> Step 8. Shows error about some route

No useful information given

**Comment by pranavbhuv** [comment]
Sorry for my bad explaining :p all these steps are what I did on *trying to use plugin* can you give a detailed turtorial? On how? When I load plugin I get a folder called maps and a file called idcounts what do I do from there? I'm using Pocketmine Protocol 113

**Comment by inxomnyaa** [comment]
> Step 5. Insert PNG (images.png) file in folder next too idcounts.json

thats actually wrong. you put it into mapapi/images

**Comment by pranavbhuv** [comment]
That's the problem I do t have the folder mapapi which then goes into images I'll try to manually make one but when my server loads only has a folder named maps and then if you go into the folder it has idcounts.json but I will try and manually make the folder I'll get back to you if it works

**Comment by inxomnyaa** [comment]
Create it.

**Comment by inxomnyaa** [comment]
![image](https://user-images.githubusercontent.com/8733998/29710296-f86590e6-898f-11e7-92fb-a30a48bf5124.png)
![image](https://user-images.githubusercontent.com/8733998/29710301-fd19dc78-898f-11e7-885b-6834a1c6804e.png)

**Comment by pranavbhuv** [comment]
Ahhh so it's in the plugins folder I'll make it there I'll get back to you

**Comment by pranavbhuv** [comment]
Thanks works :) btw do you have Kik? And my server is CastleRaid.us.to 26211 it's in beta stage..

**Comment by inxomnyaa** [comment]
Who tf does even still use kik anymore, its so 2010.. I have telegram, see my github profile or website for contact: wolvesfortress.de

**Comment by pranavbhuv** [comment]
For me /maps save is broken. :p
