### ISSUE TITLE
image folder not generating

### ISSUE THREAD

**Issue by charliegustard** [thebigsmileXD/MapAPI#15]
I get no error but the image folder is not being created anywhere.

**Comment by inxomnyaa** [comment]
https://github.com/thebigsmileXD/MapAPI/blob/master/src/xenialdan/MapAPI/Loader.php#L16-L24

They are generating at the correct folder. Probably no permission. /plugins/MapAPI/images
If not, just create it yourself :P

**Comment by charliegustard** [comment]
is it because I'm using pmmp?

**Comment by inxomnyaa** [comment]
Should not. But i only give support on pmmp

**Comment by SalmonDE** [comment]
The recursive paremeter defaults to false if not given:
http://php.net/manual/de/function.mkdir.php

**Comment by inxomnyaa** [comment]
Outdated issue - Flagged as discontinued
