### ISSUE TITLE
Regarding Issue #3

### ISSUE THREAD

**Issue by Matthww** [thebigsmileXD/MapAPI#6]
In Issue #3 @Misteboss he has a problem where the maps wouldn't save. He closed the issue since he fixed it. But didn't tell how he did... So others don't know how to fix this same problem if they have this too.

So I'm asking again how did you fix it @misteboss ?

**Comment by Thunder33345** [comment]
How do you manage to reproduce it?
if you cant it might just be some misconfiguration on their side

**Comment by Matthww** [comment]
@Thunder33345 Load in a map, restart the server and it will be gone. And @misteboss fixed it without telling how...

**Comment by inxomnyaa** [comment]
the saving is WIP.

**Comment by Matthww** [comment]
@thebigsmileXD Yea but @misteboss knows the fix..

**Comment by inxomnyaa** [comment]
well, the maps do not have saving code yet. in theory plugins could use map->save, but thats fucked up

**Comment by MisteFr** [comment]
I used an other technic,PS : this plugin is very bad cause of the time to make a map

**Comment by inxomnyaa** [comment]
@Misteboss code one yourself and we will see who's plugin better.

**Comment by MisteFr** [comment]
![img_5316](https://cloud.githubusercontent.com/assets/17687222/26643517/ddf6f228-4631-11e7-967c-86a4edd01a6c.PNG)
![img_5332](https://cloud.githubusercontent.com/assets/17687222/26643516/ddf2135c-4631-11e7-91cf-1d00c9f36f14.PNG)
![img_5333](https://cloud.githubusercontent.com/assets/17687222/26643518/ddf7f59c-4631-11e7-9d80-08bfe357b292.PNG)
Already done :)

**Comment by inxomnyaa** [comment]
totally independent of my plugin? can you use the pmmp icon once please?

and what kind of buggy core do you use that your data flags for the air breathing are there?

**Comment by Matthww** [comment]
@thebigsmileXD Tesseract probably

**Comment by MisteFr** [comment]
@Matthww Nop pocketmine :)

**Comment by Matthww** [comment]
@Misteboss Lol I don't have the bubbles on PocketMine

**Comment by MisteFr** [comment]
@thebigsmileXD They are here for a good reason, and i don't know what do you want me to do but saving map is easy

**Comment by MisteFr** [comment]
@Matthww Fake devs don't know data flag :|

**Comment by Matthww** [comment]
@Misteboss Who are you calling a fake dev? And I do know about data flag. I though this was a bug or some sort. But you did those bubbles on purpose..

**Comment by inxomnyaa** [comment]
These bubble issues were fixed back in 1.0. It was a data flag for humans. too off-toppic, locked.

**Comment by inxomnyaa** [comment]
looks like mcpe can render ANY color, not just block colors. Might rewrite

**Comment by inxomnyaa** [comment]
Anyone tested saving?
