### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by amon28** [thebigsmileXD/MapAPI#8]
I'm having trouble creating a map I put an image png (yt.png) in the maps folder I reloaded my server and In put the command /map create yt but it doesn't seem to work

**Comment by inxomnyaa** [comment]
i dont know what prople keep doing wrong, the usage is too obvious.
install plugin, make sure its folder is named "MapAPI",  put the images into the then generated mapapi/images folder, start it and /map create yt.png

**Comment by amon28** [comment]
Thanks the only problem I had the plug it didn't generate a new folder I have to make a new folder
It works now

**Comment by inxomnyaa** [comment]
It does generate the folders

the proper issue might be that the plugin folder manually got chmod-ded.
